version: '3.7'

services:
  web_dev:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db_dev
  db_dev:
    image: postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    ports:
      - 5434:5432
    env_file:
      - ./.env.dev.db

volumes:
  postgres_data_dev:
